// Administrator dashboard: overview, clinics, users, reports
function rg(id,x){const c=C.find(y=>y.id==id);if(x=='Suspended'&&!confirm('Suspend '+c.n+'?'))return;c.rg=x;c.v=x=='Verified'?1:0;note('admin','System','Clinic '+x.toLowerCase(),c.n);draw()}
function addCl(){const n=prompt('Clinic name?');if(!n)return;C.push(mk(C.length+1,'NEW-2026',n,'General Medicine','New Owner',1,0,'Pending','Open',7.826,123.437,'Pagadian City','(062) 000-0000',0,10,'',['Consultation'],['9:00 AM']));draw()}
function pie(d){const t=d.reduce((x,y)=>x+y[1],0)||1;let a=-Math.PI/2;return `<svg viewBox="-105 -105 210 210" width=210>${d.map(([l,v,c])=>{if(!v)return '';const b=a+v/t*2*Math.PI,x1=100*Math.cos(a),y1=100*Math.sin(a),x2=100*Math.cos(b),y2=100*Math.sin(b),p=v==t?`<circle r=100 fill="${c}"/>`:`<path d="M0 0L${x1} ${y1}A100 100 0 ${v/t>.5?1:0} 1 ${x2} ${y2}Z" fill="${c}" stroke="#fff" stroke-width=2 />`;a=b;return p}).join('')}</svg>`}
function adTab(t){
if(t=='ov'){const mx=Math.max(...C.map(c=>c.ap));return `<div class=grid4>${stat(C.length,'Registered Clinics',C.filter(c=>c.rg=='Verified').length+' verified','#0d9488')}${stat(C.filter(c=>c.rg=='Pending').length,'Pending Verification','awaiting review','#d97706')}${stat(C.reduce((x,c)=>x+c.ap,0),'Total Appointments','all time','#3b82f6')}${stat(U.length,'Registered Users',U.filter(u=>u.r=='Patient').length+' patients','#64748b')}</div><div class=grid2 style="margin-top:16px"><div class=card><h2>Clinic Status Overview</h2>${C.map(c=>`<div class=row><span><b>${e(c.n)}</b><br><span class=mu>${e(c.sp[0])} · ${e(c.ow)}</span></span>${pill(c.rg)}</div>`).join('')}</div><div class=card><h2>Appointments by Clinic</h2>${[...C].sort((a,b)=>b.ap-a.ap).map(c=>bar(c.n,c.ap,mx)).join('')}</div></div>`}
if(t=='clinics')return `<div class=card style="padding:0"><div class=row style="padding:20px 24px;border:0"><h2 style="margin:0">Registered Clinics</h2><button class=btn onclick="addCl()">+ Add Clinic</button></div>${C.map(c=>`<div class=row style="padding:16px 24px"><span><b>${e(c.n)}</b> <span class=mono>${c.cd}</span><br><span class=mu>${e(c.sp[0])} · Owner: ${e(c.ow)}</span><br><span class=mu style="font-size:.85rem">${c.sf} staff · ${c.ap} appointments</span></span><span style="display:flex;gap:8px;align-items:center">${pill(c.rg)}${c.rg=='Pending'?`<button class="btn s ok" onclick="rg(${c.id},'Verified')">Verify</button>`:c.rg=='Suspended'?`<button class="btn s o" onclick="rg(${c.id},'Verified')">Reinstate</button>`:`<button class="btn s o gr" onclick="rg(${c.id},'Suspended')">Manage</button>`}</span></div>`).join('')}</div>`;
if(t=='users')return `<div class=card style="padding:0"><div class=row style="padding:20px 24px;border:0"><h2 style="margin:0">System Users</h2></div>${U.map((u,i)=>`<div class=row style="padding:14px 24px"><span style="display:flex;gap:14px;align-items:center"><span class=av3 style="background:${u.r=='Patient'?'#f97316':'#3b82f6'}">${e(u.n[0])}</span><span><b>${e(u.n)}</b><br><span class=mu>${e(u.e)} · Joined ${u.d}</span></span></span><span style="display:flex;gap:10px;align-items:center"><b style="color:${u.r=='Patient'?'#f97316':'#3b82f6'};font-size:.85rem">${u.r}</b><span class=pl style="${u.a?'background:#dcfce7;color:#16a34a':'background:#f1f5f9;color:#64748b'}">${u.a?'Active':'Inactive'}</span><button class="btn s o gr" onclick="U[${i}].a^=1;draw()">${u.a?'Deactivate':'Reactivate'}</button></span></div>`).join('')}</div>`;
if(t=='rep'){const mo={},sv={},cn=x=>A.filter(a=>x=='Cancelled'?['Cancelled','Rejected'].includes(a.s):a.s==x).length;A.forEach(a=>{const m=a.date.slice(0,7);mo[m]=(mo[m]||0)+1;sv[a.svc]=(sv[a.svc]||0)+1});const ms=Object.entries(mo).sort(),mx=Math.max(1,...ms.map(x=>x[1])),sd=[['Pending','#0ea5e9'],['Approved','#22c55e'],['Completed','#f59e0b'],['Cancelled','#a78bfa']],top=Object.entries(sv).sort((a,b)=>b[1]-a[1]).slice(0,5),am=Math.max(1,...C.map(c=>c.ap)),ve=C.filter(c=>c.rg=='Verified'),av=[['Available',ve.filter(c=>c.st=='Open'||c.st=='Emergency').length,'#10b981'],['Limited',ve.filter(c=>c.st=='Limited services').length,'#f59e0b'],['Unavailable',ve.filter(c=>c.st=='Closed').length,'#ef4444']];
return `<h2>Reports & Analytics</h2><div class=grid4>${stat(A.length,'Total Appointments','','var(--tx)')}${stat(cn('Completed'),'Completed','','#16a34a')}${stat(ve.length,'Active Facilities','','#0ea5e9')}${stat(new Set(C.flatMap(c=>c.svc)).size,'Services Tracked','','#9333ea')}</div>
<div class=grid2 style="margin-top:16px"><div class=card><h2>Appointments Over Time</h2><div class=chart>${ms.map(([m,v])=>`<div style="flex:1;text-align:center"><b>${v}</b><div style="height:${v/mx*160}px;background:#0ea5e9"></div><small class=mu>${new Date(m+'-01T00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'})}</small></div>`).join('')}</div></div>
<div class=card><h2>Appointment Status Distribution</h2><div style="text-align:center">${pie(sd.map(([l,c])=>[l,cn(l),c]))}<div class=mu style="font-size:.8rem">${sd.map(([l,c])=>`<span class=lg style="background:${c};border:0"></span> ${l} (${cn(l)}) &nbsp;`).join('')}</div></div></div>
<div class=card><h2>Most Requested Services</h2>${top.map(([l,v])=>bar(l,v,top[0][1],'#22c55e')).join('')}</div>
<div class=card><h2>Service Availability Summary</h2>${av.map(([l,v,c])=>bar(l,v,ve.length||1,c,' clinics ('+Math.round(v/(ve.length||1)*100)+'%)')).join('')}<h2 style="margin-top:20px">Appointments by Facility</h2>${[...C].sort((a,b)=>b.ap-a.ap).slice(0,4).map(c=>bar(c.n,c.ap,am,'#0ea5e9')).join('')}</div></div>`}
return ''}
