// Login and registration pages for patient, staff and admin
const AU={patient:{g:'linear-gradient(160deg,#fb7a1a,#c2410c)',bg:'#fff5ec',ic:'👤',t:'Patient Portal',d:'Find clinics, check real-time availability, and book your appointment — all without leaving home.',f:[['Browse Clinics','Search by specialty or location'],['Book Instantly','Choose slots that fit your schedule'],['Track Appointments','View, reschedule, or cancel anytime']],ey:'WELCOME BACK',h:'Patient Log In',em:'Email Address',ph:'juan.dela.cruz@email.com',btn:'Log In to Patient Portal'},
staff:{g:'linear-gradient(160deg,#5ba0fa,#1d4ed8)',bg:'#eff6ff',ic:'📋',t:'Clinic Staff Portal',d:"Manage your clinic's schedule, appointment slots, and patient bookings in one dashboard.",f:[['Slot Management','Update available appointment slots'],['Schedule Control','Manage doctor and staff availability'],['Appointment Queue','Approve, reschedule, or reject bookings']],ey:'STAFF ACCESS',h:'Clinic Staff Log In',em:'Work Email',ph:'staff@clinicdomain.com',btn:'Log In to Staff Portal'},
admin:{g:'linear-gradient(160deg,#2dd4bf,#0f766e)',bg:'#effcf9',ic:'🖥',t:'System Administrator',d:'Centralized control for managing clinics, accounts, and citywide health service availability.',f:['Verify & manage clinic accounts','Monitor citywide service availability','Manage patient and staff accounts','Generate system-wide reports','Maintain the clinic map registry'],ey:'SYSTEM ACCESS',h:'Administrator Log In',em:'Admin Email',ph:'admin@lapitcare.gov.ph',btn:'Access Admin Dashboard'}};
function eye(b){const i=b.previousElementSibling;i.type=i.type=='password'?'text':'password'}
function auth(reg){const r=S.role,a=AU[r],f=(l,t='text',id='',ph='')=>`<label>${l}</label><input type=${t} id="${id||l}" placeholder="${ph}" required>`,pw=l=>`<label>${l}</label><div style="position:relative"><input type=password id="${l}" required style="padding-right:44px"><button type=button class=eye onclick="eye(this)">👁</button></div>`;
const feats=r=='admin'?`<div class=scope><small>ADMIN SCOPE</small>${a.f.map(x=>`<div>• ${x}</div>`).join('')}</div>`:a.f.map(([h,d])=>`<div style="display:flex;gap:12px;margin-bottom:16px"><span class=ck>✓</span><span><b>${h}</b><br><small>${d}</small></span></div>`).join('');
let form,foot;
if(reg){form=f('Full name')+(r=='staff'?f('Clinic name')+f('PRC / license no.'):'')+f('Phone','tel')+f('Email','email')+(r=='patient'?f('Address'):'')+pw('Password')+(r=='patient'?'<label style="display:flex;gap:8px;font-weight:400"><input type=checkbox required style="width:auto;margin:3px 0"> I consent to the collection and processing of my personal data under the Data Privacy Act of 2012 (RA 10173).</label><br>':'');foot=`<p class=mu style="text-align:center">Have an account? <a href=# class=lk onclick="go({v:'login'});return false">Log in</a></p>`}
else{form=f(a.em,'email','Email',a.ph)+(r=='staff'?f('Clinic Access Code','text','Code','e.g. SCAR-2024')+'<p class=mu style="margin:-8px 0 12px;font-size:.8rem">Provided by your clinic administrator upon registration.</p>':'')+pw('Password')+(r=='patient'?'<div style="text-align:right;margin:-6px 0 14px"><a href=# class=lk>Forgot password?</a></div>':'')+(r=='admin'?`<label>One-Time PIN <span class=mu style="font-weight:400">Sent to registered device</span></label><input id=otp inputmode=numeric maxlength=6 pattern="[0-9]{6}" placeholder="0 0 0 0 0 0" required style="text-align:center;letter-spacing:.4em;font-family:monospace;margin-bottom:4px"><div class=mu style="display:flex;justify-content:space-between;margin-bottom:16px"><small>Enter the 6-digit code from your authenticator.</small><a href=# class=lk onclick="alert('A new code was sent.');return false">Resend</a></div>`:'');
foot=r=='admin'?`<p class=mu style="text-align:center">Contact system administrator for access</p><hr style="border:0;border-top:1px solid var(--bd)"><small class=mu>🔒 Session expires after 30 minutes of inactivity. All actions are logged for audit purposes.</small>`:`<p class=mu style="text-align:center">${r=='staff'?'New staff member?':"Don't have an account?"} <a href=# class=lk onclick="go({v:'reg'});return false">Register here</a></p>`}
const ban=r=='admin'&&!reg?'<div class=rb>🛡 <span><b>Restricted Administrator Access</b><br>Authorized personnel only. All sessions are logged.</span></div>':'';
return `<div class=au><div class=au-l style="background:${a.g}"><a class=bk onclick="go({v:'home'})">← Back to Home</a><span class=aui>${a.ic}</span><h1 style="font-size:2.3rem;margin:.5em 0 .3em;line-height:1.1">${a.t}</h1><p style="opacity:.9">${a.d}</p><div style="margin-top:auto;padding:30px 0">${feats}</div><small>LapitCARE · Pagadian City${r=='admin'?' · Restricted Access':''}</small></div><div class=au-r style="background:${a.bg}"><div class=ac>${ban}<small class=eb>${reg?'CREATE ACCOUNT':a.ey}</small><h2 style="font-size:1.9rem;margin:.1em 0 1em">${reg?(r=='staff'?'Clinic Staff Registration':'Patient Registration'):a.h}</h2><form onsubmit="event.preventDefault();sub(${reg})">${form}<button class=btn style="width:100%;padding:15px;background:${a.g}">${reg?'Register':a.btn}</button></form><div style="margin-top:16px">${foot}</div></div></div></div>`}
function sub(reg){const r=S.role;if(reg&&r=='staff'){alert('Registration submitted. An administrator must verify your clinic before you can log in.');note('admin','New clinic staff registration awaiting verification.');return go({v:'login'})}
if(reg){const v=id=>document.getElementById(id)?.value;P.patient.name=v('Full name');P.patient.email=v('Email');P.patient.phone=v('Phone');P.patient.address=v('Address');U.push({n:P.patient.name,e:P.patient.email,r:'Patient',d:fd(TD),a:1})}
go({v:'app',tab:r=='patient'?'clinics':'ov',sel:null})}
