// Patient dashboard: clinics, booking steps, appointments, feedback
function clinicCard(c,adm){const k=stc[c.st];return `<div class=card style="padding:0;overflow:hidden;${c.st=='Emergency'?'border:2px solid #dc2626':''}"><div class=hd style="background:${k}"><span>● ${c.st.toUpperCase()}</span><span>👥 ${c.q} · ~${c.w}m wait</span></div><div style="padding:16px"><b style="font-size:1.1rem">${e(c.n)}</b><div class=mu>${e(c.ty)}</div>${c.al?`<div class=al>${e(c.al)}</div>`:''}<p class=mu style="line-height:1.9">📍 ${e(c.a)}<br>📞 ${c.ph}<br>✉️ ${c.em}<br>🕒 ${c.hr}</p><small><b>SPECIALTIES</b></small><div>${chips(c.sp)}</div><small><b>SERVICES</b></small><div>${chips(c.svc)}</div><div style="display:flex;gap:8px;margin-top:12px"><button class="btn s o" onclick="go({tab:'map',sel:${c.id}})">🗺 View on Map</button>${adm?`<button class="btn s ${c.v?'r':''}" onclick="tg(${c.id})">${c.v?'Deactivate':'Verify'}</button>`:`<button class="btn s" ${c.st=='Closed'?'disabled':''} onclick="S.bk={s:2,c:${c.id},sv:'',d:'',t:'',n:''};go({tab:'book'})">Book</button>`}</div></div></div>`}
function tg(id){const c=C.find(x=>x.id==id);c.v=c.v?0:1;note('admin','System','Clinic '+(c.v?'verified':'deactivated'),c.n);draw()}
function st(id,s){const a=A.find(x=>x.id==id);a.s=s;note('patient','Appointment','Appointment '+s,`Your ${a.svc} appointment on ${a.date}, ${a.t} is now ${s.toLowerCase()}.`);draw()}
function rs(id){const a=A.find(x=>x.id==id);a.s='Cancelled';S.bk={s:3,c:a.c,sv:a.svc,d:'',t:'',n:a.nt};go({tab:'book'})}
function B(o){Object.assign(S.bk,o);draw()}
function cf(){const b=S.bk,c=C.find(x=>x.id==b.c);if(taken(b.c,b.t,b.d))return alert('Slot just taken.');A.push({id:nid++,c:b.c,svc:b.sv,date:b.d,t:b.t,me:1,s:'Pending',nt:b.n});note('patient','Appointment','Booking Submitted',`${b.sv} at ${c.n} on ${b.d}, ${b.t} is pending approval.`);note('staff','Appointment','New Appointment Request',`${P.patient.name} requested ${b.sv} on ${b.d}, ${b.t}.`);S.bk={s:1,c:null,sv:'',d:'',t:'',n:''};go({tab:'appts',at:'Pending'})}
function rate(n){S.rt=n;document.querySelectorAll('.sx').forEach((x,i)=>x.style.color=i<n?'#f59e0b':'#dbe3ee')}
function sfb(){const c=+document.getElementById('ff').value,m=document.getElementById('fm').value;if(!c||!S.rt)return alert('Select a facility and a rating.');F.push({c,cat:document.getElementById('fc').value,r:S.rt,m,d:nowS()});S.rt=0;note('staff','System','New Patient Feedback','A patient left a rating.');go({ft:'hist'})}
function sv(){Object.keys(P[S.role]).forEach(k=>{const el=document.getElementById('p_'+k);if(el)P[S.role][k]=el.value});alert('Profile saved.');go({ed:0})}
function setSt(){const c=C[0],g=x=>document.getElementById(x).value;c.st=g('sts');c.q=+g('qc');c.w=+g('qw');c.al=g('qa');const em=c.st=='Emergency';note('patient',em?'Emergency':'Resource',em?'Emergency Status Alert':'Facility Status Update',`${c.n}: ${c.al||c.st}`);alert('Clinic status updated.');draw()}
function bkTab(){const b=S.bk,s=b.s,c=C.find(x=>x.id==b.c),L=['Select Facility','Select Service','Choose Date & Time','Confirm'];
let h=`<div class="card stp">${L.map((l,i)=>`<span class="${s==i+1?'on':s>i+1?'dn':''}"><i>${s>i+1?'✓':i+1}</i>${l}</span>`).join('')}</div><div class=card style="margin-top:14px">`;
if(s==1)h+=`<h2>Select a facility</h2><div class=grid>${C.filter(x=>x.v&&x.st!='Closed').map(x=>`<div class=card style="cursor:pointer" onclick="B({c:${x.id},s:2})"><b>${e(x.n)}</b><br><span class=mu>${e(x.a)}</span><br><span class=tag>${x.st}</span></div>`).join('')}</div>`;
if(s==2)h+=`<h2>Select a service · ${e(c.n)}</h2>${c.svc.map(v=>`<button class="btn o" style="margin:4px" onclick="B({sv:'${v}',s:3})">${v}</button>`).join('')}`;
if(s==3){const fr=fs(c,b.d);h+=`<h2>Choose date & time</h2><label>Date</label><input type=date min="${new Date().toISOString().slice(0,10)}" value="${b.d}" onchange="B({d:this.value,t:''})"><label>Time slot</label>${b.d?`<div>${fr.map(t=>`<button class="btn s ${b.t==t?'':'o'}" style="margin:3px" onclick="B({t:'${t}'})">${t}</button>`).join('')||'<p class=mu>No free slots.</p>'}</div>`:'<p class=mu>Pick a date first.</p>'}<br><button class=btn ${b.d&&b.t?'':'disabled'} onclick="B({s:4})">Next</button>`}
if(s==4)h+=`<h2>Confirm</h2><p><b>${e(c.n)}</b><br>${e(b.sv)} · ${b.d} at ${b.t}</p><label>Notes</label><textarea onchange="S.bk.n=this.value" placeholder="Reason for visit">${e(b.n)}</textarea><button class=btn onclick="cf()">Confirm appointment</button>`;
return h+(s>1?`<p><button class=back onclick="B({s:${s-1}})">← Back</button></p>`:'')+'</div>'}
function apTab(){const L=A.filter(a=>a.me),f=S.at,fl=x=>x=='All'?L:L.filter(a=>x=='Cancelled'?['Cancelled','Rejected'].includes(a.s):a.s==x);
return `<div class=tabs>${['All','Pending','Approved','Completed','Cancelled'].map(x=>`<button class="${f==x?'on':''}" onclick="go({at:'${x}'})">${x} <span class=bd style="background:#64748b">${fl(x).length}</span></button>`).join('')}</div>${fl(f).map(a=>`<div class=card style="margin-bottom:12px"><div class=row style="border:0;padding:0"><span><b style="font-size:1.1rem">${e(a.svc)}</b> <span class=tag>● ${a.s}</span><br><span class=mu>${e(C.find(c=>c.id==a.c).n)}</span></span><span style="text-align:right;font-family:monospace"><b>${a.date}</b><br><span class=mu>${a.t}</span></span></div><p class=mu>Patient: <b>${e(P.patient.name)}</b> &nbsp; Phone: ${e(P.patient.phone)}<br>Notes: ${e(a.nt||'—')}</p>${['Pending','Approved'].includes(a.s)?`<hr style="border:0;border-top:1px solid var(--bd)"><button class="btn s o" onclick="rs(${a.id})">Reschedule</button> <button class="btn s o r2" onclick="st(${a.id},'Cancelled')">Cancel Appointment</button>`:''}</div>`).join('')||'<p class=mu>No appointments here.</p>'}`}

function patientTab(t){const r=S.role;if(r=='patient'){
 if(t=='clinics')return `<input placeholder="Search by name, specialty, or location…" value="${e(S.q)}" onchange="S.q=this.value;draw()"><div class=grid>${C.filter(c=>c.v&&(c.n+c.sp+c.a+c.svc).toLowerCase().includes(S.q.toLowerCase())).map(c=>clinicCard(c)).join('')}</div>`;
 if(t=='book')return bkTab();
 if(t=='appts')return apTab();
 if(t=='fb'){const done=[...new Set(A.filter(a=>a.me&&a.s=='Completed').map(a=>a.c))],h=S.ft=='hist';
 return `<div class=card style="max-width:760px"><div class=tabs style="margin-top:0"><button class="${h?'':'on'}" onclick="go({ft:'new'})">📝 Submit Feedback</button><button class="${h?'on':''}" onclick="go({ft:'hist'})">📋 Feedback History (${F.length})</button></div>${h?F.map(f=>`<div class=row style="display:block"><b>${e(C.find(c=>c.id==f.c).n)}</b> <span class=tag>${f.cat}</span> <span class=mu>${f.d}</span><div style="color:#f59e0b">${stars(f.r)}</div><span class=mu>${e(f.m)}</span></div>`).join('')||'<p class=mu>No feedback yet.</p>':`<label>HEALTH FACILITY</label><select id=ff><option value="">Select a facility...</option>${done.map(i=>`<option value=${i}>${e(C.find(c=>c.id==i).n)}</option>`).join('')}</select><p class=mu style="margin-top:-8px;font-size:.8rem">Only facilities where you have a completed appointment.</p><label>CATEGORY</label><select id=fc>${['Service Quality','Cleanliness','Staff Attitude','Waiting Time'].map(x=>`<option>${x}</option>`).join('')}</select><label>RATING</label><div style="font-size:2rem;cursor:pointer;margin-bottom:10px">${[1,2,3,4,5].map(i=>`<span class=sx style="color:#dbe3ee" onclick="rate(${i})">★</span>`).join('')}</div><label>YOUR COMMENTS</label><textarea id=fm rows=4 placeholder="Share your experience with this health facility..."></textarea><button class=btn style="width:100%" onclick="sfb()">Submit Feedback</button>`}</div>`}}
return ''}
