// Clinic staff dashboard: overview, appointments, slots, clinic profile, feedback
function dr(x){C[0].dr=x;note('patient','Resource','Doctor schedule update',`${P.staff.name} is now ${x.toLowerCase()}.`);draw()}
function qq(d){C[0].q=Math.max(0,C[0].q+d);draw()}
function tgl(x){const b=C[0].bl,i=b.indexOf(x);i<0?b.push(x):b.splice(i,1);draw()}
function saveCl(){const c=C[0],g=k=>document.getElementById('cp_'+k).value;c.n=g('n');c.sp=g('sp').split(',').map(x=>x.trim()).filter(Boolean);c.a=g('a');c.ph=g('ph');c.em=g('em');c.hr=g('hr');c.svc=g('svc').split(',').map(x=>x.trim()).filter(Boolean);c.st=g('st');c.q=+g('q')||0;c.w=+g('w')||0;c.al=g('al');const em=c.st=='Emergency';note('patient',em?'Emergency':'Resource',em?'Emergency Status Alert':'Facility Status Update',`${c.n}: ${c.al||c.st}`);alert('Clinic profile saved.');draw()}
function stTab(t){const c=C[0],td=A.filter(a=>a.c==1&&a.date==TD),st1=x=>A.some(y=>y.c==1&&y.date==TD&&y.t==x&&live(y))?'Booked':c.bl.includes(x)?'Blocked':'Available',ini=P.staff.name.replace('Dr. ','').split(' ').map(w=>w[0]).join('').slice(0,2);
if(t=='ov')return `<div class=grid4>${stat(td.length,"Today's Appointments",td.filter(a=>a.s=='Pending').length+' pending','#3b82f6')}${stat(c.q,'Queue Now','patients waiting','#f97316')}${stat(TM.filter(x=>st1(x)=='Available').length,'Slots Available','of '+TM.length+' today','#16a34a')}${stat(td.filter(a=>a.s=='Completed').length,'Completed Today','as of now','#64748b')}</div>
<div class=grid2 style="margin-top:16px"><div class=card><h2>Doctor Availability</h2><div class=row style="border:0"><span style="display:flex;gap:12px;align-items:center"><span class=av2>${ini}</span><span><b>${e(P.staff.name)}</b><br><span class=mu>General Physician</span></span></span><span class=tag>${c.dr}</span></div><div class=g3>${['Available','On Leave','Unavailable'].map(x=>`<button class="sg ${c.dr==x?'on':''}" onclick="dr('${x}')">${x}</button>`).join('')}</div></div>
<div class=card><h2>Queue Management</h2><div style="display:flex;gap:14px;align-items:center"><h1 style="margin:0;color:#3b82f6;font-size:3rem">${c.q}</h1><span class=mu>patients currently<br>in queue</span></div><div class=g2 style="gap:12px;margin-top:14px"><button class=sg onclick="qq(-1)">− Remove</button><button class="btn" style="background:#3b82f6" onclick="qq(1)">+ Add</button></div></div></div>
<div class=card style="margin-top:16px"><h2>Today's Appointments</h2>${td.map(a=>`<div class=row><span><b>${e(pn(a))}</b> <span class=mu>${a.age}y/o</span><br><span class=mu>${a.t} · ${e(a.svc)}</span></span>${pill(a.s)}</div>`).join('')||'<p class=mu>None today.</p>'}</div>`;
if(t=='appts')return `<div class=card style="padding:0"><div class=row style="padding:20px 24px"><h2 style="margin:0">All Appointments</h2></div>${A.filter(a=>a.c==1).map(a=>`<div class=row style="padding:14px 24px"><span><b>${e(pn(a))}</b> <span class=mu>${a.age}y/o</span> <span class=mono>APT-${String(a.id).padStart(4,'0')}</span><br><span class=mu>${e(a.svc)}</span><br><span class=mu>${fd(a.date)} at ${a.t}</span></span><span style="display:flex;gap:8px;align-items:center">${pill(a.s)}${a.s=='Approved'?`<button class="btn s o gr" onclick="st(${a.id},'Completed')">Mark Done</button>`:''}${a.s=='Pending'?`<button class="btn s ok" onclick="st(${a.id},'Approved')">Approve</button><button class="btn s o r2" onclick="st(${a.id},'Rejected')">Reject</button>`:''}</span></div>`).join('')}</div>`;
if(t=='sl')return `<div class=card><div class=row style="border:0"><h2 style="margin:0">Today's Appointment Slots</h2><span class=mu>${new Date(TD+'T00:00').toLocaleDateString('en-US',{dateStyle:'long'})}</span></div><div class=g5>${TM.map(x=>{const k=st1(x),a=A.find(y=>y.c==1&&y.date==TD&&y.t==x&&live(y));return `<div class="slot ${k}" ${k=='Booked'?'':`onclick="tgl('${x}')"`}><b>${x}</b><br>${k}${a?`<br><span class=mu>${e(pn(a).split(' ')[0])}</span>`:''}</div>`}).join('')}</div><p class=mu><span class="lg" style="border-color:#86efac"></span> Available &nbsp; <span class="lg" style="border-color:#93c5fd"></span> Booked &nbsp; <span class="lg" style="border-color:#cbd5e1"></span> Blocked &nbsp; · tap Available/Blocked to toggle</p></div>`;
if(t=='cp'){const I=(k,l,v)=>`<div><label>${l}</label><input id=cp_${k} value="${e(v)}"></div>`;return `<div class=card style="max-width:780px"><h2>Clinic Profile</h2><div class=g2>${I('n','Clinic name',c.n)}${I('sp','Specialties (comma-separated)',c.sp.join(', '))}</div>${I('a','Address',c.a)}<div class=g2>${I('ph','Phone',c.ph)}${I('em','Email',c.em)}</div>${I('hr','Operating hours',c.hr)}${I('svc','Services (comma-separated)',c.svc.join(', '))}<h2>Operational status</h2><div class=g2><div><label>Status</label><select id=cp_st>${['Open','Limited services','Closed','Emergency'].map(x=>`<option ${c.st==x?'selected':''}>${x}</option>`).join('')}</select></div>${I('q','Queue count',c.q)}</div><div class=g2>${I('w','Estimated wait (min)',c.w)}${I('al','Alert message (shown on dashboards)',c.al)}</div><button class=btn onclick="saveCl()">Save clinic profile</button> <button class="btn o r2" style="margin-left:8px" onclick="go({v:'home'})">Log out</button></div>`}
if(t=='fb')return `<div class=card><h2>Patient Feedback</h2>${F.filter(f=>f.c==1).map(f=>`<div class=row><span style="color:#f59e0b">${stars(f.r)} <span class=tag>${f.cat}</span><br><span class=mu>${e(f.m)}</span></span><span class=mu>${f.d}</span></div>`).join('')||'<p class=mu>No feedback yet.</p>'}</div>`;return ''}
